# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)


Beach.create(	name:"	William Randolph Hearst Memorial State Beach	",	phone:"	805-927-2020	",	url:"	http://www.parks.ca.gov/?page_id=589	",	description:"	The beach is located near the historic town of San Simeon along Highway One and gives visitors the opportunity to hike, swim, fish and beachcomb. A popular beach spot, this protected cove also offers visitors pier fishing and deep-sea fishing from chartered boats. Ocean kayaking is also popular. Picnic tables, barbecue grills and restrooms are available. This day use area offers 24 picnic sites, 150 parking spaces, restrooms, water faucets, barbecue grill stands and easy beach access. Recreational activities include picnicking, swimming, fishing, boating, kayaking and sunbathing. There is a kayak and boogie board concession in operation with equipment for rent.	",	address_street:"	750 Hearst Castle Road	",	address_city:"	San Simeon	",	address_state:"	CA	",	address_zip:"	93452	",	county:"	San Luis Obispo	",	latitude:"	35.643603	",	longitude:"	-121.187861	", 	parking:	TRUE	,	parking_price:"		",	lifeguard:		,	restroom:		,	surfing:		,	firepit:		,	volleyball:		,	dog:		,	fishing:	TRUE	,	hours:"	Dawn to Dusk	")
Beach.create(	name:"	Butterfly Beach	",	phone:"		",	url:"	https://www.santabarbara.com/activities/beaches/butterfly/	",	description:"	Across from the Four Seasons Biltmore, this beach is deceptive in its simplicity. Since it is a Montecito Beach, and Montecito and the Biltmore have more than their share of celebrities, you have a good chance of seeing somebody famous here.	",	address_street:"	1176 Channel Dr	",	address_city:"	Montecito	",	address_state:"	CA	",	address_zip:"	93108	",	county:"	Santa Barbara	",	latitude:"	34.41718	",	longitude:"	-119.645025	", 	parking:	FALSE	,	parking_price:"		",	lifeguard:	FALSE	,	restroom:	FALSE	,	surfing:		,	firepit:		,	volleyball:		,	dog:		,	fishing:		,	hours:"		")
Beach.create(	name:"	Silver Strand Beach	",	phone:"	(619) 435-5184	",	url:"	http://www.parks.ca.gov/?page_id=654	",	description:"	Silver Strand State Beach features extensive beaches on both the Pacific Ocean and San Diego Bay. Combined with the area’s mild climate, the beaches make Silver Strand one of the area’s finest recreation destinations. Camping, swimming, surfing, boating, water-skiing, volleyball, and picnicking are popular activities. Anglers can fish for perch, corbina, grunion and yellow-fin croaker.	",	address_street:"	5000 Highway 75	",	address_city:"	Coronado	",	address_state:"	CA	",	address_zip:"	92118	",	county:"	Ventura 	",	latitude:"	32.6349631	",	longitude:"	-117.1423041	", 	parking:	TRUE	,	parking_price:"		",	lifeguard:	TRUE	,	restroom:	TRUE	,	surfing:	TRUE	,	firepit:		,	volleyball:		,	dog:	FALSE	,	fishing:		,	hours:"		")
Beach.create(	name:"	Santa Monica State Beach	",	phone:"	310-458-8300	",	url:"	http://www.smgov.net/portals/beach/	",	description:"	Santa Monica State Beach	",	address_street:"	200 Santa Monica Pier	",	address_city:"	Santa Monica	",	address_state:"	CA	",	address_zip:"	90401	",	county:"	Los Angeles	",	latitude:"	34.0150456	",	longitude:"	-118.5038705	", 	parking:	TRUE	,	parking_price:"		",	lifeguard:	TRUE	,	restroom:	TRUE	,	surfing:	TRUE	,	firepit:	FALSE	,	volleyball:	TRUE	,	dog:		,	fishing:	true 	,	hours:"	24 hours	")
Beach.create(	name:"	Seal Beach	",	phone:"	(562) 431-2527	",	url:"	http://www.sealbeachca.gov/	",	description:"	The second longest wooden pier in California (the longest is in Oceanside) is located in Seal Beach and is used for fishing and sightseeing. The pier has periodically suffered severe damage due to storms and other mishaps, requiring extensive reconstruction.	",	address_street:"	888 Ocean Avenue	",	address_city:"	Seal Beach	",	address_state:"	Ca	",	address_zip:"	90740	",	county:"	Orange County	",	latitude:"	33.7392678	",	longitude:"	-118.1045985	", 	parking:	TRUE	,	parking_price:"		",	lifeguard:	TRUE	,	restroom:		,	surfing:		,	firepit:	FALSE	,	volleyball:	FALSE	,	dog:		,	fishing:		,	hours:"		")
Beach.create(	name:"	Ponto Beach	",	phone:"	(619) 438-3143	",	url:"	http://www.sandiegocoastlife.com/san-diego-beaches/beaches-ponto-beach.html	",	description:"	A Real Gem South Ponto Beach is a rare gem in that it is one of the widest beaches in the county and exists in an undeveloped area. Coast Hwy 101 hugs the shoreline here, with Batiquitos Lagoon on the other side of the highway. The beach is a popular family destination, and only one of the few beaches in the area that has public restrooms and showers.	",	address_street:"	County Hwy S21	",	address_city:"	Carlsbad	",	address_state:"	CA	",	address_zip:"	92024	",	county:"	San Diego 	",	latitude:"	33.082858	",	longitude:"	-117.309866	", 	parking:	TRUE	,	parking_price:"	8	",	lifeguard:	TRUE	,	restroom:		,	surfing:	TRUE	,	firepit:		,	volleyball:	TRUE	,	dog:	FALSE	,	fishing:		,	hours:"	6:00am - 10:00pm	")